### ISSUE TITLE
OAuth fails when browser/charm/gitlab are on different hosts

### ISSUE THREAD

**Issue by pedroleaoc** [finos/legend-integration-juju#26]
The Legend bundle and the GitLab instance need to be in the same computer or the authentication process fails. This means gitlab.com and EKS deployments will always fail.

**Comment by claudiubelu** [comment]
We've solved this issue by using the nginx ingress integrator charms and using the Kubernetes Service names instead of IPs. Additionally, the Legend Studio, SDLC, and Engine charms can be configured with custom DNS names as well. With the changes below, we won't have to update the Callback URLs every time the Pod IPs get updated due to various reasons.

Related:

https://github.com/finos/legend-juju-libs/pull/5
https://github.com/finos/legend-juju-libs/pull/8
https://github.com/finos/legend-juju-libs/pull/9
https://github.com/finos/legend-juju-studio-operator/pull/7
https://github.com/finos/legend-juju-sdlc-server-operator/pull/9
https://github.com/finos/legend-juju-engine-server-operator/pull/8
https://github.com/finos/legend-juju-engine-server-operator/pull/9
https://github.com/finos/legend-juju-sdlc-server-operator/pull/10

We can close this issue now.
