### ISSUE TITLE
Juju creates applications with the wrong ports

### ISSUE THREAD

**Issue by pedroleaoc** [finos/legend-integration-juju#28]
We need to work on a PR for each charm to correct this issue.

**Comment by pedroleaoc** [comment]
https://github.com/finos/legend-juju-libs/pull/5

**Comment by claudiubelu** [comment]
When deploying an application, Juju also creates a service with the same name as the application. This service has a default port
of ``65536/TCP``. In order to properly use the Service names directly, we need that port to point to the right port.

Fixed by:

https://github.com/finos/legend-juju-libs/pull/5
https://github.com/finos/legend-juju-libs/pull/9
https://github.com/finos/legend-juju-studio-operator/pull/7
https://github.com/finos/legend-juju-sdlc-server-operator/pull/9
https://github.com/finos/legend-juju-engine-server-operator/pull/8

The above PRs merged, we can close the issue.
